version: '3.2'
services:

  php:
    image: php:fpm-alpine3.13
    restart: always
    container_name: php
    volumes:
      - /var/nfs:/var/www/html
    networks:
      - mynet
    deploy:
      replicas: 3
      placement:
        constraints:
          - "node.role == worker"
  nginx:
    image: nginx:alpine
    restart: always
    container_name: nginx
    volumes:
      - /var/nfs:/var/www/html/
      - /var/nfs/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - mynet
    deploy:
      replicas: 3
      placement:
        constraints:
          - "node.role == worker"
networks:
  mynet:
    driver: overlay
